<a href="https://colab.research.google.com/github/va11h411a/Jobsheet-AI-course/blob/main/jobsheet_2_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([[80, 30, 25],
[50, 20, 10]])
B = np.array([[30, 60, 15],
[10, 30, 30]])

hasil = A + B
print (hasil)

[[110  90  40]
 [ 60  50  40]]


In [ ]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.cross(A, B)
print (hasil)

[-305 -110  350]


In [ ]:
import numpy as np
a = np.array ([[3,1],[2,0]])
b = np.array ([[2,1],[1,-1]])
c = np.array ([[-1, 1, 2],[2,0,-1]])

hasil = np.dot(b,c)
print (hasil)

[[ 0  2  3]
 [-3  1  3]]


In [ ]:
import math

a = math.factorial(8)
b = math.factorial(5)

print (a/b)

336.0


In [ ]:
import numpy as np

a = np.array ([5, 3, 7])
b = np.array ([12, -3, 1])

print (np.cross(a,b))

[ 24  79 -51]


In [2]:
print ('hello world')

hello world
